# Generated by Django 4.2.17 on 2024-12-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirQualityIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("pmTwoPointFive", models.FloatField()),
                ("pmTen", models.FloatField()),
                ("nitrogendioxide", models.FloatField()),
                ("sulphurdioxide", models.FloatField()),
                ("carbonmonxide", models.FloatField()),
                ("Proximity_to_Industrial_Areas", models.FloatField()),
                ("Population_Density", models.IntegerField()),
                ("AirQualityIndex", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(name="Student",),
    ]
