# Generated by Django 4.2.17 on 2024-12-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_airqualityindex_delete_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airqualityindex",
            old_name="AirQualityIndex",
            new_name="air_quality",
        ),
    ]
