# Generated by Django 4.2.17 on 2024-12-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_airqualityindex_airqualityindex_air_quality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airqualityindex",
            name="temperature",
            field=models.FloatField(default=0.0),
        ),
    ]
