# Generated by Django 4.2.17 on 2024-12-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_airqualityindex_temperature"),
    ]

    operations = [
        migrations.RemoveField(model_name="airqualityindex", name="air_quality",),
    ]
